restaurant_review/me/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    
    path('', ProfileView.as_view(), name='profile'),
    path('bookmark/', ProfileBookMarkView.as_view(), name='profile_bookmark'),
    path('edit/', ProfileEditView.as_view(), name='profile_edit'),
    path('bookmark/add/<int:restaurant_id>/', AddToFavoritesView.as_view(), name='add_to_favorites'),
    
]

restaurant_review/restaurant/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', RestaurantMainView.as_view(), name='restaurant_main'),
    
    path('category/', RestaurantListView.as_view(), name='restaurant_list'),
    path('<int:id>/', RestaurantDetailsView.as_view(), name='restaurant_details'),
    path('edit/<int:id>/', RestaurantEditView.as_view(), name='restaurant_edit'),
    path('create/', RestaurantCreateView.as_view(), name='restaurant_create'),
    path('delete/<int:id>/', RestaurantDeleteView.as_view(), name='restaurant_delete'),

    path('favourite/<int:restaurant_id>/', RestaurantFavourite.as_view(), name='restaurant_favourite'),
    # path('category/', RestaurantCreateView.as_view(), name='Restaurant List'),
]

restaurant_review/restaurant_review/urls.py
# restaurant_review/restaurant_review/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authen/', include('authen.urls')),
    path('reviews/', include('reviews.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('me/', include('me.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    
    
    path('api/', include('api.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant_review/reviews/models.py
# restaurant_review/restaurant/models.py
from django.db import models
from django.contrib.auth.models import User


# UserProfile model to add extra user info
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Link to Django's User model
    phone_number = models.CharField(default='Unknown', max_length=15)
    about_me = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', null=True, blank=True)

    def __str__(self):
        return self.user.username


# RestaurantType remains unchanged
class RestaurantType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


# Restaurant model
class Restaurant(models.Model):
    no_storefront = models.BooleanField(default=False)
    storefront = models.BooleanField(default=False)
    delivery = models.BooleanField(default=False)
    pickup = models.BooleanField(default=False)

    PRICE_RANGE_CHOICES = [
        ('LOW', 'ราคาต่ำกว่า 100 บาท'),
        ('MEDIUM', 'ราคามากกว่า 100 บาท'),
        ('HIGH', 'ราคามากกว่า 500 บาท'),
        ('PREMIUM', 'ราคามากกว่า 1,000 บาท'),
    ]

    name = models.CharField(max_length=255)
    price_range = models.CharField(max_length=20, choices=PRICE_RANGE_CHOICES)
    province = models.CharField(max_length=100, default='Unknown')
    district = models.CharField(max_length=100, default='Unknown')
    subdistrict = models.CharField(max_length=100, default='Unknown')
    phone_number = models.CharField(max_length=15)

    # Allow latitude and longitude to be nullable
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Link to the owner of the restaurant
    restaurant_types = models.ManyToManyField(RestaurantType, through='RestaurantRestaurantType')

    def __str__(self):
        return self.name


# Many-to-Many relationship between Restaurant and RestaurantType
class RestaurantRestaurantType(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    restaurant_type = models.ForeignKey(RestaurantType, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('restaurant', 'restaurant_type')


# Operating Hours for a restaurant
class OperatingHour(models.Model):
    DAY_OF_WEEK_CHOICES = [
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    ]

    TIME_CHOICES = [
        ('00:00', '00:00'), ('00:30', '00:30'),
        ('01:00', '01:00'), ('01:30', '01:30'),
        ('02:00', '02:00'), ('02:30', '02:30'),
        ('03:00', '03:00'), ('03:30', '03:30'),
        ('04:00', '04:00'), ('04:30', '04:30'),
        ('05:00', '05:00'), ('05:30', '05:30'),
        ('06:00', '06:00'), ('06:30', '06:30'),
        ('07:00', '07:00'), ('07:30', '07:30'),
        ('08:00', '08:00'), ('08:30', '08:30'),
        ('09:00', '09:00'), ('09:30', '09:30'),
        ('10:00', '10:00'), ('10:30', '10:30'),
        ('11:00', '11:00'), ('11:30', '11:30'),
        ('12:00', '12:00'), ('12:30', '12:30'),
        ('13:00', '13:00'), ('13:30', '13:30'),
        ('14:00', '14:00'), ('14:30', '14:30'),
        ('15:00', '15:00'), ('15:30', '15:30'),
        ('16:00', '16:00'), ('16:30', '16:30'),
        ('17:00', '17:00'), ('17:30', '17:30'),
        ('18:00', '18:00'), ('18:30', '18:30'),
        ('19:00', '19:00'), ('19:30', '19:30'),
        ('20:00', '20:00'), ('20:30', '20:30'),
        ('21:00', '21:00'), ('21:30', '21:30'),
        ('22:00', '22:00'), ('22:30', '22:30'),
        ('23:00', '23:00'), ('23:30', '23:30'),
        ('23:59', '23:59'),
    ]

    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    day_of_week = models.CharField(max_length=10, choices=DAY_OF_WEEK_CHOICES)
    opening_time = models.CharField(max_length=5, choices=TIME_CHOICES)
    closing_time = models.CharField(max_length=5, choices=TIME_CHOICES)

    def __str__(self):
        return f"{self.restaurant.name} - {self.day_of_week}"


# Reviews of a restaurant
class Review(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)  # Link to Restaurant
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Link to User who wrote the review
    rating = models.IntegerField()
    title = models.CharField(max_length=255, default='Reviews Title')
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review by {self.user.username} for {self.restaurant.name}"


# Favorite restaurants for a user
class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Link to the User
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)  # Link to the Restaurant
    favorited_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} favorited {self.restaurant.name}"


# Images associated with a review
class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)  # Link to Review
    image_file = models.ImageField(upload_to='review_images/', null=True, blank=True)
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)  # Who uploaded the image
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image for {self.review.restaurant.name} by {self.review.user.username}"


# Images associated with a restaurant
class RestaurantImage(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)  # Link to Restaurant
    image_file = models.ImageField(upload_to='restaurant_images/')
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)  # Who uploaded the image
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image for {self.restaurant.name}, uploaded by {self.uploaded_by.username}"

restaurant_review/restaurant/forms.py
from django import forms
from reviews.models import Restaurant, RestaurantType

class RestaurantCreateForm(forms.ModelForm):
    restaurant_types = forms.ModelMultipleChoiceField(
        queryset=RestaurantType.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Restaurant
        fields = ['name', 'price_range', 'no_storefront', 'storefront', 'delivery', 'pickup', 'phone_number', 'province', 'district', 'subdistrict', 'latitude', 'longitude', 'restaurant_types']


class RestaurantEditForm(forms.ModelForm):
    restaurant_types = forms.ModelMultipleChoiceField(
        queryset=RestaurantType.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Restaurant
        fields = ['name', 'price_range', 'no_storefront', 'storefront', 'delivery', 'pickup', 'latitude', 'longitude', 'restaurant_types']

# class RestaurantForm(forms.ModelForm):
#     name = forms.CharField(max_length=255)
#     price_range = forms.ChoiceField(choices=Restaurant.PRICE_RANGE_CHOICES)
#     province = forms.CharField(max_length=100, required=False, initial='Unknown')
#     district = forms.CharField(max_length=100, required=False, initial='Unknown')
#     subdistrict = forms.CharField(max_length=100, required=False, initial='Unknown')
    
#     # Make latitude and longitude not required
#     latitude = forms.DecimalField(required=False)
#     longitude = forms.DecimalField(required=False)

#     # Modify the clean methods to handle optional values
#     def clean_latitude(self):
#         latitude = self.cleaned_data.get('latitude')
#         if latitude is not None and (latitude < -90 or latitude > 90):
#             raise forms.ValidationError("Latitude must be between -90 and 90 degrees.")
#         return latitude

#     def clean_longitude(self):
#         longitude = self.cleaned_data.get('longitude')
#         if longitude is not None and (longitude < -180 or longitude > 180):
#             raise forms.ValidationError("Longitude must be between -180 and 180 degrees.")
#         return longitude

#     # Boolean fields for service types
#     no_storefront = forms.BooleanField(required=False)
#     storefront = forms.BooleanField(required=False)
#     delivery = forms.BooleanField(required=False)
#     pickup = forms.BooleanField(required=False)

#     # Multiple choice field for restaurant types
#     restaurant_types = forms.ModelMultipleChoiceField(
#         queryset=RestaurantType.objects.all(),
#         widget=forms.CheckboxSelectMultiple,
#         required=False
#     )

restaurant_review/restaurant/templates/restaurant_form.html
<!-- restaurant_review/restaurant/templates/restaurant_form.html -->
{% extends "layout.html" %}
{% load static %}

{% block title %}
    เพิ่มร้านอาหารใหม่
{% endblock %}

{% block content %}
<h1 class="text-center text-2xl font-bold mb-4">เพิ่มร้านอาหารใหม่</h1>

<div class="flex justify-center">
    <form method="post" class="w-full max-w-lg">
        
    
        {% csrf_token %}
        <h1 class="text-left text-sm font-bold mb-4 mt-9">ข้อมูลพื้นฐาน</h1>
        <div class="bg-white p-6 rounded shadow-md my-5">
            <div class="mb-4">
                <label for="name" class="block text-sm font-medium text-gray-700">ชื่อร้าน</label>
                <input required type="text" name="name" id="name" value="{{ form.name.value|default:'' }}" class="font-highlight w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500">
            </div>
        
            <div class="mb-4">
                <label class="block text-sm font-medium text-gray-700">รูปแบบบริการ</label>
            
                <div class="form-check my-2">
                    <input type="checkbox" id="no_storefront" name="no_storefront" 
                           class="font-highlight mr-2 px-2 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                           {% if form.no_storefront.value %}checked{% endif %}>
                    <label for="no_storefront">No Storefront</label>
                </div>
            
                <div class="form-check my-2">
                    <input type="checkbox" id="storefront" name="storefront" 
                           class="font-highlight mr-2 px-2 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                           {% if form.storefront.value %}checked{% endif %}>
                    <label for="storefront">Storefront</label>
                </div>
            
                <div class="form-check my-2">
                    <input type="checkbox" id="delivery" name="delivery" 
                           class="font-highlight mr-2 px-2 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                           {% if form.delivery.value %}checked{% endif %}>
                    <label for="delivery">Delivery</label>
                </div>
            
                <div class="form-check my-2">
                    <input type="checkbox" id="pickup" name="pickup" 
                           class="font-highlight mr-2 px-2 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                           {% if form.pickup.value %}checked{% endif %}>
                    <label for="pickup">Pickup</label>
                </div>
            </div>
            
        
            <div class="mb-4">
                <label for="price_range" class="block text-sm font-medium text-gray-700">ช่วงราคา</label>
                <select name="price_range" class="font-highlight w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                    {% for choice in form.price_range.field.choices %}
                        <option value="{{ choice.0 }}" {% if form.price_range.value == choice.0 %}selected{% endif %}>{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-4">
                <label for="phone_number" class="block text-sm font-medium text-gray-700">เบอร์โทรติดต่อ</label>
                <input required type="text" name="phone_number" id="phone_number" value="{{ form.phone_number.value|default:'' }}" class="font-highlight w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500">
            </div>

            <div class="mb-4">
                <label for="restaurant_types" class="block text-sm font-medium text-gray-700">ประเภทของร้านอาหาร</label>
                <!-- Add 'overflow-y-auto' and 'max-h-52' to make it scrollable with a height limit -->
                <div class="font-highlight w-full px-3 py-2 border border-gray-300 rounded-md overflow-y-auto max-h-52">
                    {% for choice in form.restaurant_types.field.queryset %}
                        <div class="mb-2">
                            <label>
                                <input type="checkbox" name="restaurant_types" value="{{ choice.pk }}" 
                                       {% if choice.pk in form.restaurant_types.value %}checked{% endif %}>
                                {{ choice }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
            </div>
            
            
            

            <!-- ปุ่มเพิ่มฟิลด์ใหม่ -->
            <label for="day_of_week" class="block text-sm font-medium my-3 text-gray-700">ช่วงเวลาเปิด-ปิด</label>
            <div id="operating-hours-container">
                <template id="operating-hour-template">
                    <div class="operating-hour flex space-x-4 mb-4">
                        <!-- วัน -->
                        <select name="day_of_week[]" class="w-1/4 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                            <option value="Monday">Monday</option>
                            <option value="Tuesday">Tuesday</option>
                            <option value="Wednesday">Wednesday</option>
                            <option value="Thursday">Thursday</option>
                            <option value="Friday">Friday</option>
                            <option value="Saturday">Saturday</option>
                            <option value="Sunday">Sunday</option>
                        </select>
            
                        <!-- เวลาเปิด -->
                        <select name="opening_time[]" class="w-1/4 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                            <option value="00:00">00:00</option>
                            <option value="00:30">00:30</option>
                            <option value="01:00">01:00</option>
                            <option value="01:30">01:30</option>
                            <option value="02:00">02:00</option>
                            <option value="02:30">02:30</option>
                            <option value="03:00">03:00</option>
                        </select>
            
                        <!-- เวลาปิด -->
                        <select name="closing_time[]" class="w-1/4 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                            <option value="00:00">00:00</option>
                            <option value="00:30">00:30</option>
                            <option value="01:00">01:00</option>
                            <option value="01:30">01:30</option>
                            <option value="02:00">02:00</option>
                            <option value="02:30">02:30</option>
                            <option value="03:00">03:00</option>
                        </select>
            
                        <!-- ปุ่มลบ -->
                        <button type="button" class="remove-hour w-1/12 flex justify-center items-center px-1 py-1 text-red-500 hover:text-red-700 focus:outline-none">
                            <svg class="w-[24px] h-[24px] text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.1" d="m15 9-6 6m0-6 6 6m6-3a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                            </svg>
                        </button>
                    </div>
                </template>
            </div>
            
            <button type="button" id="add-operating-hour" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded my-4">
                เพิ่มช่วงเวลาเปิด-ปิด
            </button>
            
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    const addOperatingHourBtn = document.getElementById('add-operating-hour');
                    const container = document.getElementById('operating-hours-container');
                    const template = document.getElementById('operating-hour-template');

                    // Event listener to add new operating hour component
                    addOperatingHourBtn.addEventListener('click', function() {
                        const clone = template.content.cloneNode(true);  // Clone the template content
                        container.appendChild(clone);
                    });

                    // Remove operating hour row on clicking the remove button
                    container.addEventListener('click', function(event) {
                        if (event.target.closest('.remove-hour')) {
                            event.target.closest('.operating-hour').remove();
                        }
                    });
                });

            </script>
            
            

        </div>
        
    

        <div class="bg-white p-6 rounded shadow-md">
            <div class="flex justify-start items-center mt-9 mb-5 gap-10">
                <h1 class="text-left text-sm font-bold">ที่อยู่</h1>
                <p id="toggle-location" class="text-xs underline cursor-pointer">ใช้ Google Maps</p>
            </div>
        
            <!-- Dropdown Location -->
            <section id="dropdown-location">
                <div class="mb-4">
                    <label for="provinceDropdown" class="block text-sm font-medium text-gray-700">จังหวัด</label>
                    <select id="provinceDropdown" name="provinceDropdown" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                        <option value="">เลือกจังหวัด</option>
                    </select>
                </div>
        
                <div class="mb-4">
                    <label for="districtDropdown" class="block text-sm font-medium text-gray-700">เขต/อำเภอ</label>
                    <select id="districtDropdown" name="districtDropdown" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                        <option value="">เลือกเขต/อำเภอ</option>
                    </select>
                </div>
        
                <div class="mb-4">
                    <label for="subdistrictDropdown" class="block text-sm font-medium text-gray-700">ตำบล</label>
                    <select id="subdistrictDropdown" name="subdistrictDropdown" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                        <option value="">เลือกตำบล</option>
                    </select>
                </div>
            </section>
        
            <!-- Google Maps Location -->
            <section id="googlemaps-picker-location" style="display:none;">
                <!-- ปุ่มให้ผู้ใช้กดเพื่อหาตำแหน่งของตัวเอง -->
                <a id="find-location-btn" class="text-blue-500 underline cursor-pointer mb-4 inline-flex items-center">
                    <svg class="w-5 h-5 mr-2 text-blue-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8-8 8-8 8 3.59 8 8-3.59 8-8 8zM12 8c-1.1 0-2 .9-2 2h4c0-1.1-.9-2-2-2zm0 6c-1.1 0-2-.9-2-2h4c0 1.1-.9 2-2 2z"/>
                    </svg>
                    ใช้ตำแหน่งของฉัน
                </a>
        
                <!-- แผนที่จะแสดงที่นี่ -->
                <div id="map" class="w-full h-64"></div>
            </section>
        
            <!-- Hidden fields สำหรับบันทึกข้อมูลจาก Google Maps -->
            <section id="hidden-location-fields" style="display:none;">
                <input type="hidden" id="id_latitude" name="latitude">
                <input type="hidden" id="id_longitude" name="longitude">
                <input type="hidden" id="id_province" name="province">
                <input type="hidden" id="id_district" name="district">
                <input type="hidden" id="id_subdistrict" name="subdistrict">
            </section>
        </div>
        
        
        <!-- โหลด Google Maps API -->
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDvte_IcXyAxq7Bwv_0MrmrmPaEwW89yFg&callback=initMap" async defer></script>
        <script src="{% static 'js/googlemaps_location.js' %}" defer></script>
        <script src="{% static 'js/location.js' %}"></script>
        


        
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 mb-4 mt-9 text-white font-bold py-2 px-14 rounded">
            บันทึก
        </button>
    </form>
        
</div>
{% endblock %}